[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Scott Lundberg and Marco Tulio Ribeiro", email = "scott.lundberg@microsoft.com"},
]
dependencies = [
    "setuptools>=68.2.2",
    "aiohttp",
    "diskcache",
    "gptcache",
    "msal",
    "nest_asyncio",
    "numpy",
    "openai>=0.27.8",
    "platformdirs",
    "pygtrie",
    "pyparsing>=3.0.0",
    "requests",
    "tiktoken>=0.3",
    "loguru>=0.7.2",
    "text-generation>=0.6.1",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
Homepage = "https://github.com/slundberg/guidance"

[project.optional-dependencies]
docs = [
    "ipython",
    "nbsphinx",
    "numpydoc",
    "sphinx",
    "sphinx_rtd_theme",
]
test = [
    "pytest",
    "pytest-cov",
    "torch",
    "transformers",
]

[tool.pdm.dev-dependencies]
ipy = [
    "ipykernel>=6.26.0",
]
